server.port=8080

# HANA datasource
spring.datasource.driver-class-name=com.sap.db.jdbc.Driver
spring.datasource.url=jdbc:sap://6b042fee-9347-4496-87f7-7f627893a66e.hna1.prod-us10.hanacloud.ondemand.com:443?encrypt=true&validateCertificate=true&currentschema=53763232895C40AC8B538B9294047814
spring.datasource.username=53763232895C40AC8B538B9294047814_EGGV1Y2T7F46SZF3IE40AYISC_RT
spring.datasource.password=YyA0ZPOnd|i0hm^J-*MCTj(,6G.+&xS`nDq;Mg)|~9TWN1B9GXEdUCWFEPI:!0+_YCp=gTSAPOG_QU!g]T(=,)*=A~u0s8-%k)|Z;M52{|(~[|4f#|4=Pjz|PNf:@T(=